version: '3'
services:
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass1wd
      MONGO_INITDB_DATABASE: zeta
    volumes:
      - ./db-init.js:/docker-entrypoint-initdb.d/init.js:ro
    ports:
      - '27017-27019:27017-27019'
  api:
    image: NodeJS
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass1wd
      ME_CONFIG_MONGODB_SERVER: zeta
    depends_on:
      - database
  ui:
    build: .
    image: zeta-admin
    depends_on:
      - database
    ports:
      - 8082:5000
